name: Release to Docker Hub

on:
  push:
    branches:
      - release

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and tag Docker image
        run: docker build -t devstroop/container-management:beta .

      - name: Push Docker image to Docker Hub
        run: docker push devstroop/container-management:beta
        
